org: joaopauloantunes
app: aws-python-http-api-project
service: aws-python-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  # stage: ${self:custom.currentStage}
  stage: dev
  # Uses improved resolution of lambda version hashes (see: https://www.serverless.com/framework/docs/deprecations/#default-providerlambdahashingversion)
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  sum:
    handler: handler.sum
    events:
      - http:
          path: /
          method: post
  update_user:
    handler: handler.update_user
    events:
      - http:
          path: /users/{user_id}
          method: put
  delete_user:
    handler: handler.delete_user
    events:
      - http:
          path: /users/{user_id}
          method: delete
  
plugins:
  - serverless-python-requirements
